import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App wink wink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.root} ${styles.bgRed}`}>
        <h1>Riko you are awesome bro {new Date().toDateString()}</h1>
        <nav className={`${styles.nav}`}>
          <Link href="/about/">About</Link>
          <Link href="/about/mabout">Mabout</Link>
        </nav>
        <div className="bg-green-300 flex flex-row justify-center justify-around ">
          <h3>Hello </h3>
          <h3>Riko</h3>
        </div>
      </div>
    </>
  );
}
